{% set version = "6.1.2" %}

package:
  name: pyface
  version: {{ version }}

source:
  fn: pyface-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/p/pyface/pyface-{{ version }}.tar.gz
  sha256: 7c2ac3d5cbec85e8504b3b0b63e9307be12c6d710b46bae372ce6562d41f4fbc

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - traits
    - pygments
  run:
    - python
    - traits
    - pygments

test:
  imports:
    - pyface

about:
  home: http://docs.enthought.com/pyface/
  home: https://github.com/enthought/pyface
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Traits-capable windowing framework
  description: |
    pyface project contains a toolkit-independent GUI abstraction layer,
    which is used to support the "visualization" features of the Traits
    package.
  doc_url: http://docs.enthought.com/pyface/
  doc_source_url: https://github.com/enthought/pyface/blob/master/docs/source/index.rst
  dev_url: https://github.com/enthought/pyface

extra:
  recipe-maintainers:
    - grlee77
