travis:
  secure:
    BINSTAR_TOKEN: GUU58qNxVhlo3ai1A+wEo/g41HCw1U1UUTT3wdz1KyqQqArJSHjIvNVYU/kah8ZLWpcuvCAYAuXpLTp+e5OwVCh069Fgw7eHn5zvkqQpVjVNDP/epv3R/ltNThBFsc28p+kLKvq+I+QA/EM0v/hH46jyTGABVlw6Oiaafdx8cSzNkEkqSq7bNbxJUHgpb5KoQPevZeDOyBgq1ZNoJSzoGKn5/s4DHR5as0DqU8ZtoKt2KXpvORBuO5+oyg3bpEPCzcgGZCl2jpCZcGtDZSVx57z0QUA8UC2zdK0ejrND0zHQWz8BOWD1KxLB0aa1jw8XQLRNX1QHMrrmCPkpkj89aGS72Lnmd3y43DIUYejeAmBDZjhn8YvYY1m/+PC2OPq88GzBUc9LA+0NqoFDV0WtAodj31S3rPGni13aMDHU/DmKG4QD+QCr0juORigGSpnLySiNQTE/5C41qKjCBeVrA2352CVkECQ+8hm82KtgmVEhUW0HreU9h7/GcncSL2DN7nZwljEaHoRcUywsYadzKEnxOxKcm6nkbyYSPgYDR690Zxkqga8lXewKAPX2+yjOuISHE1GZEqWK5nC3V/uhBLi6jDuyhzqR67Xj30uiPAxU1VzuV4BmJ7fc8iwE0QmzLmMiOBHAiB8O+bWTUDo3TdcwUKzdJuoi1ynZ8l20Q+A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
